create table Budget (
	id bigint generated by default as identity (start with 1), 
	description varchar(255), 
	name varchar(40) not null, 
	state varchar(255), 
	year integer check (year<=9999 AND year>=1900), 
	budgets_id bigint,
	primary key (id)
)

create table Budgets (
	id bigint generated by default as identity (start with 1), 
	username varchar(255) not null, 
	selectedBudget_id bigint, 
	primary key (id), 
	unique (username)
)
